import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
import { ThemeSwitcher } from './components/themeSwitcher/themeSwitcher';
import Nav from './components/nav/nav';
import Footer from './components/footer/footer';

export const metadata: Metadata = {
  title: 'Protect Oregon Watersheds',
  description: 'Generated by create next app',
};

// when looking at next.js docs, we are using app routing instead of page routing
// custom component styling? : https://nextui.org/docs/customization/custom-variants

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Nav />
          <main className="">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
